"""
signals.py — Detection signal functions.

Each function takes raw text and returns a float in [0, 1],
where values closer to 1 indicate more AI-like characteristics.
"""

import json
import os
import re
import string

from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_groq_client = Groq(api_key=os.environ.get('GROQ_API_KEY'))

_GROQ_MODEL = 'llama-3.3-70b-versatile'

_GROQ_PROMPT = """You are a text classification system. Analyze the text below and determine whether it was written by a human or generated by an AI.

Consider specific evidence: word choice patterns, sentence rhythm, use of hedging or filler language, personal/idiosyncratic details, repetitive phrasing, and overall naturalness of tone.

Respond with JSON only — no explanation, no markdown, no extra text. Use exactly this shape:
{"verdict": "ai" or "human", "confidence": a float between 0.0 and 1.0}

"confidence" must reflect fine-grained certainty based on the strength of the evidence you observed — use precise values (e.g. 0.63, 0.78, 0.91), not round numbers like 0.7, 0.8, or 0.9, unless the evidence genuinely is that extreme. A confidence of 1.0 should be reserved only for text with unmistakable, unambiguous signals.

Text to analyze:
"""


def groq_score(text: str) -> float:
    """
    Signal 1: Groq LLM holistic judgment.
    Returns a float in [0, 1] where 1.0 = confidently AI-generated.

    Sends text to Groq and expects JSON: {"verdict": "ai"|"human", "confidence": float}.
    If verdict is "human", flips the score: 1.0 - confidence.
    Falls back to 0.5 if the response cannot be parsed after one retry.
    """
    score = _call_groq(text)
    if score is not None:
        return score

    # Retry once on parse failure.
    score = _call_groq(text)
    return score if score is not None else 0.5


def _call_groq(text: str) -> float | None:
    """Makes one Groq API call and parses the result. Returns None on failure."""
    try:
        response = _groq_client.chat.completions.create(
            model=_GROQ_MODEL,
            messages=[
                {'role': 'user', 'content': _GROQ_PROMPT + text},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)

        verdict = parsed.get('verdict', '').lower()
        confidence = float(parsed.get('confidence', 0.5))
        confidence = max(0.0, min(1.0, confidence))  # clamp to [0, 1]

        if verdict == 'ai':
            return round(confidence, 4)
        elif verdict == 'human':
            return round(1.0 - confidence, 4)
        else:
            return None

    except Exception:
        return None


def combine_scores(groq_score: float, stylometric_score: float) -> float:
    """
    Combines Signal 1 (Groq) and Signal 2 (stylometry) into a single
    confidence score using the weighting from planning.md:
        confidence = (0.6 * groq_score) + (0.4 * stylometric_score)
    Returns the raw float, unrounded.
    """
    return (0.6 * groq_score) + (0.4 * stylometric_score)


def get_attribution_label(confidence: float) -> str:
    """
    Maps a combined confidence score to a label category.
    Boundaries (from planning.md):
        0.00 <= score < 0.35  -> "likely_human"
        0.35 <= score <= 0.65 -> "uncertain"
        0.65 < score <= 1.00  -> "likely_ai"
    Scores of exactly 0.35 or 0.65 fall into "uncertain".
    """
    if confidence < 0.35:
        return 'likely_human'
    elif confidence <= 0.65:
        return 'uncertain'
    else:
        return 'likely_ai'


def get_label_text(confidence: float) -> str:
    """
    Maps a confidence score to the exact transparency label string shown to users.
    Uses the same thresholds as get_attribution_label().
    """
    if confidence < 0.35:
        return 'This content shows strong signals of human authorship.'
    elif confidence <= 0.65:
        return (
            'We could not confidently determine whether this content is '
            'AI-generated or human-written. Mixed signals were detected.'
        )
    else:
        return 'This content shows strong signals of AI generation.'


def stylometric_score(text: str) -> float:
    """
    Measures surface-level statistical uniformity in writing style.
    Returns a score in [0, 1] where 1 = highly AI-like uniformity.

    Three sub-signals, equally weighted:
      1. Sentence length variance  — low variance → AI-like
      2. Type-token ratio (TTR)    — low lexical diversity → AI-like
      3. Punctuation density variance — low variance across sentences → AI-like
    """
    sentences = _split_sentences(text)

    if len(sentences) < 2:
        # Not enough structure to measure variance meaningfully.
        return 0.5

    sentence_var_score = _sentence_length_score(sentences)
    ttr_score = _type_token_score(text)
    punct_score = _punctuation_variance_score(sentences)

    return round((sentence_var_score + ttr_score + punct_score) / 3.0, 4)


# ---------------------------------------------------------------------------
# Sub-signal helpers
# ---------------------------------------------------------------------------

def _sentence_length_score(sentences: list[str]) -> float:
    """
    Low variance in per-sentence word counts → score near 1 (AI-like).
    Uses a decay function: score = 1 / (1 + variance / SCALE).
    SCALE of 20 means a variance of 20 words² maps to a neutral 0.5.
    """
    SCALE = 20.0
    word_counts = [len(s.split()) for s in sentences]
    mean = sum(word_counts) / len(word_counts)
    variance = sum((wc - mean) ** 2 for wc in word_counts) / len(word_counts)
    return 1.0 / (1.0 + variance / SCALE)


def _type_token_score(text: str) -> float:
    """
    Low type-token ratio (fewer unique words relative to total) → score near 1.
    Score = 1 - TTR, so a TTR of 0.4 (low diversity) → score 0.6 (AI-like).
    """
    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5
    ttr = len(set(words)) / len(words)
    return 1.0 - ttr


def _punctuation_variance_score(sentences: list[str]) -> float:
    """
    Low variance in punctuation density across sentences → score near 1 (AI-like).
    Punctuation density per sentence = punct_chars / total_chars.
    Uses the same decay: score = 1 / (1 + variance / SCALE).
    SCALE of 0.005 puts a typical AI-like variance near 0.5.
    """
    SCALE = 0.005
    punct_set = set(string.punctuation)

    densities = []
    for s in sentences:
        if not s:
            continue
        punct_count = sum(1 for c in s if c in punct_set)
        densities.append(punct_count / len(s))

    if len(densities) < 2:
        return 0.5

    mean = sum(densities) / len(densities)
    variance = sum((d - mean) ** 2 for d in densities) / len(densities)
    return 1.0 / (1.0 + variance / SCALE)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    """Split on sentence-ending punctuation followed by whitespace."""
    raw = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s.strip() for s in raw if s.strip()]
